// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wwsrxzllhsfndjezvnws.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3c3J4emxsaHNmbmRqZXp2bndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2NzIxNjgsImV4cCI6MjA0NzI0ODE2OH0.q-KVY2qu3Qrc7a29oualEHVn07pAbK9uR2hkUBHbobg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);